language: node_js
node_js:
    - 14

services: mongodb
cache:
    directories:
        - node_modules

before_install:
    - npm i -g npm@6.14.8
install:
    - npm install

script:
    - npm run test

branches:
    only:
        - Pipeline_Testing
        - master
