language: node_js
node_js:
    - 'stable'

services:
    - mongodb
cache:
    directories:
        - node_modules

install:
    - npm install

script:
    - npm run test

branches:
    only:
        - Pipeline_Testing
